import sys

sys.path.append("../cleanrl")

MW_DATA_DIR = "/PATH/TO/METAWORLD_DATA_DIR/"
CAPTION_PATH = MW_DATA_DIR
REWARD_CKPT_DIR = "/PATH/TO/REWARD_MODEL_CHECKPOINT_DIR/"
DATA_PATH = MW_DATA_DIR
EXP_DIR = "/PATH/TO/EXPERIMENT_OUTPUT_DIR/"

# For RoboCLIP only
sys.path.append("../MIL-NCE_HowTo100M")
WORD2VEC_PATH = "/PATH/TO/MIL-NCE_HowTo100M/data/word2vec.pth"
